### ISSUE TITLE
你好，请问如何安装成redis服务呢？

### ISSUE THREAD

**Issue by nottellyou** [ZeroSlayer/redis-6.2.3-stable-windows-64bit#1]
你好，请问如何安装成redis服务呢？

**Comment by ZeroSlayer** [comment]
如果你对redis安装有疑问的话，我推荐你去这个网址看看[Redis 安装 | 菜鸟教程 (runoob.com)](https://www.runoob.com/redis/redis-install.html)，这里有很详细的reids教程，虽然教程旧了些，但也能用。

**Comment by NightZed** [comment]
@nottellyou 如果你对redis安装有疑问的话，我推荐你去这个网站看看[Redis 安装 | 菜鸟教程 (runoob.com)](https://www.runoob.com/redis/redis-install.html)，这里有很详细的redis教程，虽然教程旧了些，但也能用。

**Comment by Basti-Fantasti** [comment]
Hi,

you can use [redistray](https://github.com/moonpyk/RedisTray) to launch the server.
Than it at least runs in the Windows tray instead of a command window

**Comment by Basti-Fantasti** [comment]
hmmm the redistray doesn't seem to work with the current versions or on Windows 10 anymore

**Comment by my9988** [comment]
you can visit zkteco-home/redis-windows ,native port for windows,installed as service

**Comment by nottellyou** [comment]
@my9988   think you!
@ZeroSlayer  多谢提供网址。不过，还是用redis的最新版比较好。
